// Copyright 2009-2014 Matvei Stefarov <me@matvei.org>

namespace fCraft {
    /// <summary> Enumeration of all standard Minecraft Classic block types. </summary>
    public enum Block : byte
    {
        Undefined = 255, // for error checking

        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        Plank = 5,
        Sapling = 6,
        Admincrete = 7,
        Water = 8,
        StillWater = 9,
        Lava = 10,
        StillLava = 11,
        Sand = 12,
        Gravel = 13,
        GoldOre = 14,
        IronOre = 15,
        Coal = 16,
        Log = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        RedWool = 21,
        OrangeWool = 22,
        YellowWool = 23,
        LimeWool = 24,
        GreenWool = 25,
        TealWool = 26,
        AquaWool = 27,
        CyanWool = 28,
        BlueWool = 29,
        IndigoWool = 30,
        PurpleWool = 31,
        MagentaWool = 32,
        PinkWool = 33,
        BlackWool = 34,
        GrayWool = 35,
        WhiteWool = 36,
        YellowFlower = 37,
        RedFlower = 38,
        BrownMushroom = 39,
        RedMushroom = 40,
        Gold = 41,
        Iron = 42,
        DoubleSlab = 43,
        Slab = 44,
        Brick = 45,
        TNT = 46,
        Books = 47,
        MossyCobblestone = 48,
        Obsidian = 49,

        CobblestoneSlab = 50,
        Rope = 51,
        Sandstone = 52,
        Snow = 53,
        Fire = 54,
        LightPinkWool = 55,
        ForestGreenWool = 56,
        BrownWool = 57,
        DeepBlueWool = 58,
        TurquoiseWool = 59,
        Ice = 60,
        Tile = 61,
        Magma = 62,
        Pillar = 63,
        Crate = 64,
        StoneBrick = 65
    }
}